"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

DATA_FILES = [('dep',['dep/viewer.html','dep/pg.png']),
              ('requests',['requests/cacert.pem'])]

setup(
    name="PhotoGrabber",
    data_files=DATA_FILES,
    setup_requires=['py2app'],
    app=['pg.py'],
    options=dict(py2app=dict(argv_emulation=True,iconfile='dep/pg.icns')),
)
