# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sat Oct 27 14:06:05 2012

import wx

class wxFrameLogin(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrameLogin.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, -1, "Step 1) Click the button below to authenticate PhotoGrabber with Facebook.", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.button_login = wx.Button(self.panel_1, -1, "Login to Facebook")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxFrameLogin.__set_properties
        self.SetTitle("PhotoGrabber")
        self.SetSize((400, 200))
        self.panel_1.SetMinSize((400, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxFrameLogin.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1_1.Add(self.text_ctrl_1, 1, wx.EXPAND, 0)
        sizer_1_1.Add(self.button_login, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_1_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    # PhotoGrabber glue

    def Setup(self, state):
        self.state = state
        self.button_login.Bind(wx.EVT_BUTTON, self.Submit)

    def Submit(self, event):
        self.state.toToken()
