# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sat Oct 27 14:06:05 2012

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class wxFrameOptions(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrameOptions.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_4 = wx.Panel(self, -1)
        self.text_ctrl_4 = wx.TextCtrl(self.panel_4, -1, "Step 4) Select your download options.", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.checkbox_1 = wx.CheckBox(self.panel_4, -1, "Tagged photos")
        self.checkbox_2 = wx.CheckBox(self.panel_4, -1, "Full Albums of tagged photos")
        self.checkbox_3 = wx.CheckBox(self.panel_4, -1, "Albums uploaded by the user")
        self.checkbox_4 = wx.CheckBox(self.panel_4, -1, "Comments and Tagging Information")
        self.button_options = wx.Button(self.panel_4, -1, "Begin Download!")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxFrameOptions.__set_properties
        self.SetTitle("PhotoGrabber")
        self.SetSize((400, 200))
        self.panel_4.SetMinSize((400, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxFrameOptions.__do_layout
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4_1.Add(self.text_ctrl_4, 1, wx.EXPAND, 0)
        sizer_4_1.Add(self.checkbox_1, 0, 0, 0)
        sizer_4_1.Add(self.checkbox_2, 0, 0, 0)
        sizer_4_1.Add(self.checkbox_3, 0, 0, 0)
        sizer_4_1.Add(self.checkbox_4, 0, 0, 0)
        sizer_4_1.Add(self.button_options, 1, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_4_1)
        sizer_4.Add(self.panel_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    # PhotoGrabber glue

    def Setup(self, state):
        self.state = state
        self.button_options.Bind(wx.EVT_BUTTON, self.Submit)

    def Submit(self, event):
        self.state.toFolder()

# end of class wxFrameOptions
