# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sat Oct 27 14:06:05 2012

import wx

class wxFrameToken(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrameToken.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.text_ctrl_2 = wx.TextCtrl(self.panel_2, -1, "Step 2) Paste your login token in the field below:", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.text_ctrl_token = wx.TextCtrl(self.panel_2, -1, "", style=wx.TE_MULTILINE)
        self.button_token = wx.Button(self.panel_2, -1, "Process Token")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxFrameToken.__set_properties
        self.SetTitle("PhotoGrabber")
        self.SetSize((400, 200))
        self.panel_2.SetMinSize((400, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxFrameToken.__do_layout
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_1.Add(self.text_ctrl_2, 1, wx.ALL | wx.EXPAND, 0)
        sizer_2_1.Add(self.text_ctrl_token, 1, wx.EXPAND, 0)
        sizer_2_1.Add(self.button_token, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_2_1)
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    # PhotoGrabber glue

    def Setup(self, state):
        self.state = state
        self.button_token.Bind(wx.EVT_BUTTON, self.Submit)

    def Submit(self, event):
        # TODO SANATIZE INPUT?
        self.state.token = self.text_ctrl_token.GetValue()
        self.state.toChooser()
